[package]
name = "myassembler"
version = "0.1.0"
authors = ["Rick Dearman <rick@rdearman.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos= "0.12.0"
clap = "2.33.3"
